# Generated by Django 4.0.3 on 2022-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_created_at_alter_campaign_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='logo',
        ),
    ]
